### ISSUE TITLE
Test to verify error on creating too small filesystem

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/testing#107]
We've bumped our minimum Stratis filesystem size to 512 MiB. We should write two tests, one for stratisd_cert.py and one for stratis_cli_cert.py to verify that an error is returned on a too low filesystem size, say 256 MiB.

**Comment by bgurney-rh** [comment]
It turns out that I could reuse the `test_filesystem_create_specified_size_toosmall` tests, which attempt to create a filesystem at a size of 4096 bytes.  I created another pair of tests to attempt creation of a filesystem at 512 MiB - 4096 bytes.
