### ISSUE TITLE
Stress the D-Bus monitor based testing to ensure elegant and useful exit on a few error conditions

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/testing#84]
* Make sure code behaves robustly when it is requested that the script run, but it is not found. I expect we'll have to write a more useful exception for this condition.
* Check the behavior of the stratisd_cert.py tests when the monitor script terminates before communicate() is invoked in tearDown() in stratisd_cert.py

**Comment by bgurney-rh** [comment]
I think it's so difficult to try and suppress the FileNotFoundError traceback, that we should just leave it, and have the other traceback to indicate that the script was not found.
