### ISSUE TITLE
Log every instance where D-Bus monitor script catches a signal and processes it

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/testing#89]
This happens every time we call ```interfaces_added```, ```interfaces_removed```, and ```properties_changed```. It might be worthwhile to  investigate a python logging tool, rather than just printing to stderr.

**Comment by mulkieran** [comment]
There is a link for logging in Python here; https://docs.python.org/3/howto/logging.html, but we should _start_ w/ printing to stderr, just to see what we get.

**Comment by bgurney-rh** [comment]
OK, I started an early draft PR, which seems to print messages to stdout.  If I start the monitor_dbus_signals.py script manually, while creating a test pool and filesystem, I seem to see this behavior:

- Starting the monitor_dbus_signals.py script results in a "Properties changed." stdout line.
- Creating a pool results in two "Interfaces added" stdout lines.
- Creating a filesystem on that pool results in one "Interfaces added" line.
- Destroying the filesystem results in one "Interfaces removed" line.
- Destroying the pool results in two "Interfaces removed" lines.

Does this sound like the behavior we're looking for?

**Comment by mulkieran** [comment]
Yes. What you're seeing is definitely what I would expect.

**Comment by mulkieran** [comment]
i just realized that the "properties changed" log entry is wrong, I've made a note on the PR.

**Comment by mulkieran** [comment]
This is complete.
